main: lv.id.bonne.animalpenpaper.AnimalPenPlugin
bootstrapper: lv.id.bonne.animalpenpaper.AnimalPenBootstrap
load: STARTUP

name: AnimalPenPlugin
version: ${pluginVersion}
api-version: ${apiVersion}
description: A remake of Animal Pens mod into Paper plugin version
website: "https://github.com/BONNePlayground/AnimalPenPaperized"