name: AnimalPenPlugin
version: '1.0.0'
main: lv.id.bonne.animalpenpaper.AnimalPenPlugin
description: Animal Pen Plugin
api-version: '1.21.8'
bootstrapper: lv.id.bonne.animalpenpaper.AnimalPenBootstrap
load: STARTUP